import { Copy, Check, Database, Eye } from 'lucide-react';
import { useState } from 'react';

export default function SupabaseGuide() {
  const [copied, setCopied] = useState(false);

  const sqlCode = `-- 1. CRIAR TABELA DE CONFIGURAÇÕES DO SITE
CREATE TABLE IF NOT EXISTS site_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_empresa VARCHAR(255) DEFAULT 'GIGANET',
  logo_url TEXT,
  whatsapp VARCHAR(50) DEFAULT '5511999999999',
  telefone VARCHAR(50) DEFAULT '(11) 4004-9999',
  email VARCHAR(255) DEFAULT 'contato@giganetfibra.com.br',
  endereco TEXT DEFAULT 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
  instagram VARCHAR(100) DEFAULT 'giganet_fibra',
  facebook VARCHAR(100) DEFAULT 'giganetfibra'
);

-- INSERIR DADOS INICIAIS DE CONFIGURAÇÃO (OPCIONAL)
INSERT INTO site_config (nome_empresa, whatsapp, telefone, email, endereco, instagram, facebook)
VALUES ('GIGANET', '5511999999999', '(11) 4004-9999', 'contato@giganetfibra.com.br', 'Av. Paulista, 1000 - Bela Vista - SP', 'giganet_fibra', 'giganetfibra')
ON CONFLICT DO NOTHING;

-- 2. CRIAR TABELA DE PLANOS
CREATE TABLE IF NOT EXISTS planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  velocidade VARCHAR(100) NOT NULL,
  preco NUMERIC(10,2) NOT NULL,
  beneficios JSONB DEFAULT '[]'::jsonb, -- Armazena a lista de benefícios
  destaque BOOLEAN DEFAULT false,
  ativo BOOLEAN DEFAULT true
);

-- INSERIR PLANOS PADRÃO GIGANET
INSERT INTO planos (nome, velocidade, preco, beneficios, destaque, ativo)
VALUES 
('Plano Smart 500 Mega', '500 MEGA', 99.90, '["100% Fibra Óptica", "Wi-Fi incluso", "Download ilimitado", "Suporte técnico humanizado"]'::jsonb, false, true),
('Plano Ultra 800 Mega', '800 MEGA', 129.90, '["100% Fibra Óptica", "Wi-Fi Dual Band incluso", "Download e Upload de alta performance", "Ideal para jogos e streaming", "Instalação expressa"]'::jsonb, true, true)
ON CONFLICT DO NOTHING;

-- 3. CRIAR TABELA DE LEADS DE COBERTURA
CREATE TABLE IF NOT EXISTS leads_cobertura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  whatsapp VARCHAR(50) NOT NULL,
  cep VARCHAR(10) NOT NULL,
  rua VARCHAR(255) NOT NULL,
  numero VARCHAR(50) NOT NULL,
  bairro VARCHAR(150) NOT NULL,
  status VARCHAR(50) DEFAULT 'novo', -- 'novo', 'em atendimento', 'finalizado'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-[#101835] border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6">
      <div className="flex items-center space-x-3 pb-4 border-b border-slate-800">
        <div className="p-3 rounded-xl bg-brand-purple/20 text-brand-bright-blue">
          <Database size={22} />
        </div>
        <div>
          <h3 className="font-display font-extrabold text-lg text-white">Instruções de Banco de Dados (Supabase)</h3>
          <p className="text-xs text-slate-450 text-slate-400 mt-1">
            Copie o código SQL abaixo e rode no painel de controle do seu Supabase para criar as tabelas.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {/* Step-by-step description */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs font-medium text-slate-300">
          <div className="p-3 bg-slate-900 rounded-xl border border-slate-850">
            <span className="text-brand-neon font-bold block mb-1">Passo 1: Criar Projeto</span>
            Crie uma conta gratuita no <span className="text-white">Supabase.com</span> e inicie um novo projeto chamado "Giganet".
          </div>
          <div className="p-3 bg-slate-900 rounded-xl border border-slate-850">
            <span className="text-brand-neon font-bold block mb-1">Passo 2: Executar SQL</span>
            Clique em <span className="text-white">"SQL Editor"</span> no menu esquerdo do Supabase, clique em "New query" e cole o código abaixo.
          </div>
          <div className="p-3 bg-slate-900 rounded-xl border border-slate-850">
            <span className="text-brand-neon font-bold block mb-1">Passo 3: Credenciais</span>
            Copie a <span className="text-white">API URL</span> e a <span className="text-white">Anon Key</span> e configure na Vercel ou no arquivo .env.
          </div>
        </div>

        {/* Code Box */}
        <div className="relative">
          <button
            onClick={handleCopy}
            className="absolute top-3 right-3 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center space-x-1.5 z-10"
          >
            {copied ? (
              <>
                <Check size={14} className="text-brand-neon" />
                <span className="text-brand-neon">Copiado!</span>
              </>
            ) : (
              <>
                <Copy size={14} />
                <span>Copiar SQL</span>
              </>
            )}
          </button>
          
          <pre className="text-[11px] font-mono leading-relaxed bg-[#070B19] p-5 rounded-2xl border border-slate-850 h-[360px] overflow-y-auto text-slate-400 select-all no-scrollbar">
            {sqlCode}
          </pre>
        </div>
      </div>
    </div>
  );
}
